export const myprojects =[
 {id:1, projectTitle: "Portfolio (2)", category: ["css","html"], about: "A Responsive Portfolio for personal use You can show Your Work in it With Many of Improvements .... ", imgpath: "/projects/1.png", live: "https://hazem11.vercel.app/", Github: "" , videoLink:"https://www.youtube.com/embed/l_8UUQ596ek" },
 {id:2,  projectTitle: "Portfolio (3)", category: ["css","html"], about: "A Responsive Portfolio for personal use You can show Your Work in it.  With some Addition ....", imgpath: " /projects/6.png", live: "https://hazem-port-f.vercel.app/", Github: "" , videoLink:" https://www.youtube.com/embed/dQw4w9WgXcQ" },
 {id:3,  projectTitle: "Electrical Store", category: ["css","html"], about: "FrontEnd Responsive Electric Store ....", imgpath: " /projects/10.png", live: "https://cars-nine-chi.vercel.app/", Github: "" , videoLink:"" },
 {id:4,  projectTitle: "Coffee Shop", category: ["css","html"], about: "FrontEnd Responsive coffee Shop ....", imgpath: " /projects/5.png", live: "https://hazem1.vercel.app/", Github: "" , videoLink:"" },
 {id:5,  projectTitle: "Ramadan Cards", category: ["css","html"], about: "You Can Generate Celebrateing card To Your Friend And Your Family Using his Name .... ", imgpath: " /projects/4.png", live: "https://ramadan-46h.vercel.app/", Github: "https://github.com/hazem257/ramadan-46h.git" ,  videoLink:""},
 {id:6,  projectTitle: "Premier Market", category: ["react", "full stack"], about: "This is A System To Manage Market like Add & Show order and Client ....  ", imgpath: " /projects/9.PNG", live: "https://final2-ten.vercel.app/", Github: "https://github.com/hazem257/final2.git" },
 {id:7,  projectTitle: "Portfolio (1)", category: ["css","html"], about: "A Responsive Portfolio for personal use You can show Your Work in it ....", imgpath: " /projects/3.png", live: "https://h1-iota.vercel.app/", Github: "" , videoLink:""  },
 {id:8,  projectTitle: "Quraan Player", category: ["css","html"], about: " You Can Listen To Your Favourite Quran reader With many different recitations .....", imgpath: " /projects/q.PNG", live: "https://hazem11.vercel.app/_pages/index.html", Github: "" , videoLink:""  },
 {id:9,  projectTitle: "Modern Portfolio", category: ["react"], about: "A Responsive Portfolio for personal use You can show Your Work in it With Many of Improvements And Some Animation ....", imgpath: " /projects/11.png", live: "https://modern-portfolio-2-522x.vercel.app/", Github: "https://github.com/hazem257/modern-portfolio-2-.git" , video:""},
 {id:10 ,projectTitle:"" ,category:"" ,about:"" ,imgpath:"" ,live:"",Github:"" , videoLink:""}

]
